fix: add @AllArgsConstructor
SOOLZZI/recipe-service pull request #2
Opened 2022-08-24 07:26 UTC by asyooniverse

2022-08-24 07:27 UTC, phjppo0918 approved these changes

2022-08-24 07:27 UTC, phjppo0918 commented on src/main/java/com/haruhanjan/recipeservice/entity/Recipe.java
> +@Builder
Builder 패턴이 필요할까?

2022-08-24 07:38 UTC, phjppo0918 requested changes

2022-08-24 07:38 UTC, phjppo0918 commented on src/main/java/com/haruhanjan/recipeservice/dto/CreateRecipeRequestDTO.java
> +    private List<RecipeIngredient> ingredients;
재료들도 다 Request로 받아야 하지 않나???

2022-08-24 07:38 UTC, phjppo0918 commented on src/main/java/com/haruhanjan/recipeservice/dto/CreateRecipeRequestDTO.java
> +    private List<RecipeProcess> processes;
레시피 과정도 마찬가지

2022-08-24 07:38 UTC, phjppo0918 commented on src/main/java/com/haruhanjan/recipeservice/dto/CreateRecipeRequestDTO.java
> +    private String title;
title에 getter가 있어야 하는 이유는?

2022-08-24 07:38 UTC, phjppo0918 commented on src/main/java/com/haruhanjan/recipeservice/dto/ModifyRecipeRequsetDTO.java
> +public class ModifyRecipeRequsetDTO {
getter와 Setter가 둘 다 필요한 이유는?

2022-08-24 07:38 UTC, phjppo0918 commented on src/main/java/com/haruhanjan/recipeservice/dto/RecipeResponseDTO.java
> +    private List<RecipeIngredient> ingredients;
응답할 때 그대로 엔티티를 보여줄 것이 아니라, 응답 dto를 생성하는게 좋지 않을까

2022-08-24 07:38 UTC, phjppo0918 commented on src/main/java/com/haruhanjan/recipeservice/dto/RecipeResponseDTO.java
> +    private List<RecipeProcess> processes;
레시피 과정도 마찬가지

2022-08-26 03:08 UTC, asyooniverse commented on src/main/java/com/haruhanjan/recipeservice/entity/Recipe.java
> +@Builder
필요한 데이터만 설정할 수 있고
유연성을 확보할 수 있고
가독성을 높일 수 있고
변경 가능성을 최소화할 수 있어서
Builder를 사용했습니다.

2022-08-26 03:13 UTC, asyooniverse commented on src/main/java/com/haruhanjan/recipeservice/dto/CreateRecipeRequestDTO.java
> +    private String title;
CreateRecipeRequestDTO 에 @Setter 을 붙여놔서 title 위에 붙인 @Getter 은 삭제했습니다.

2022-08-26 03:15 UTC, asyooniverse commented on src/main/java/com/haruhanjan/recipeservice/dto/ModifyRecipeRequsetDTO.java
> +public class ModifyRecipeRequsetDTO {
modify 특성 상 값을 가져와서 수정해야 하기 때문에 @Getter과 @Setter을 둘 다 붙였습니다 !!

2022-08-26 05:26 UTC, merged